name: CI workflow on PR

on:
  pull_request:
    branches:
      - master
      - main

jobs:

  print_timestamp: 
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        run: |
          echo "TIMESTAMP=$(TZ='America/Los_Angeles' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Print timestamp
        run: |
          echo "Execution time (Pacific Time Zone) $TIMESTAMP"

  lint_and_test:
    runs-on: ubuntu-latest
    needs: print_timestamp
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1


      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      # Temporarily allow the workflow to continue even if linting fails
      - name: Lint
        run: npm run lint || echo "Linting errors ignored temporarily"
      
      - name: Test
        run: npm test

